import sqlite3
import os

DB_FILE = "approvals.db"

def init_db():
    """
    Initializes the SQLite database and creates the 'pending_approvals' table if it does not exist.
    The table stores:
      - id: Unique identifier for each pending response.
      - customer_phone: The customer's phone number.
      - customer_query: The original query text.
      - generated_response: The answer generated by the LangChain agent.
      - timestamp: When the record was created.
      - approved: Integer flag (0 = pending, 1 = approved).
    """
    conn = sqlite3.connect(DB_FILE)
    c = conn.cursor()
    c.execute('''
        CREATE TABLE IF NOT EXISTS pending_approvals (
            id TEXT PRIMARY KEY,
            customer_phone TEXT,
            customer_query TEXT,
            generated_response TEXT,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
            approved INTEGER DEFAULT 0
        )
    ''')
    conn.commit()
    conn.close()

def add_pending_approval(pending_id, customer_phone, customer_query, generated_response):
    """
    Inserts a new pending approval record into the database.
    """
    conn = sqlite3.connect(DB_FILE)
    c = conn.cursor()
    c.execute('''
        INSERT INTO pending_approvals (id, customer_phone, customer_query, generated_response, approved)
        VALUES (?, ?, ?, ?, 0)
    ''', (pending_id, customer_phone, customer_query, generated_response))
    conn.commit()
    conn.close()

def get_pending_approval(pending_id):
    """
    Retrieves a pending approval record by its unique id.
    Returns a dictionary with the record's details if found, otherwise returns None.
    """
    conn = sqlite3.connect(DB_FILE)
    c = conn.cursor()
    c.execute('SELECT id, customer_phone, customer_query, generated_response, timestamp, approved FROM pending_approvals WHERE id = ?', (pending_id,))
    row = c.fetchone()
    conn.close()
    if row:
        return {
            "id": row[0],
            "customer_phone": row[1],
            "customer_query": row[2],
            "generated_response": row[3],
            "timestamp": row[4],
            "approved": row[5]
        }
    else:
        return None

def mark_approved(pending_id):
    """
    Updates a pending approval record by setting its approved status to 1.
    """
    conn = sqlite3.connect(DB_FILE)
    c = conn.cursor()
    c.execute('UPDATE pending_approvals SET approved = 1 WHERE id = ?', (pending_id,))
    conn.commit()
    conn.close()
